## Exercise 1: NumPy: Create an array with values ranging from 50 to 100

[ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


In [6]:
import numpy as np

In [3]:
Arr = np.arange(50,101)
print(Arr)

[ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


## Exercise 2: Add a border around an existing array
##### Hint: np.pad()

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
Arro = np.ones((3,3))
Arro

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
Arro = np.pad(Arro,pad_width = 1,mode = 'constant',constant_values = 0)
Arro

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

## Exercise 3: Convert a list and tuple into arrays

List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]


In [8]:
list1 = [1, 2, 3, 4, 5, 6, 7, 8]
Arr = np.asarray(list1)
print (list1)
print (Arr)

[1, 2, 3, 4, 5, 6, 7, 8]
[1 2 3 4 5 6 7 8]


In [9]:
tuple1 = (8,4,6,1,2,3)
Arrt= np.asarray(tuple1)
print(Arrt)

[8 4 6 1 2 3]


## Also try np.asarray for the problem above! 

## Exercise 4:  Convert the values of Centigrade degrees into Fahrenheit degrees

In [28]:
Arr = np.array([-17.77777778,-11.11111111,7.33888889,1.11111111,37.72777778])
list1 = []

In [29]:
for i in Arr:
    FA = ((i* 9/5) + 32)
    FA = '%2f'%FA
    list1.append(FA)
print(list1)

['-0.000000', '12.000000', '45.210000', '34.000000', '99.910000']


Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


## Exercise 5: Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. 

Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


In [39]:
Arr = np.array([1,2,3], dtype=np.float64)
Arr

array([1., 2., 3.])

In [42]:
print('Size of the array:',Arr.size)
print('Length of one array element in bytes:',Arr.itemsize)
print('Total bytes consumed by the elements of the array:',Arr.nbytes)

Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24


## Exercise 6: Get the unique elements of an array

Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]


In [45]:
Arr = np.array([10,10,20,20,30,30])
Arr = np.unique(Arr)
Arr

array([10, 20, 30])

In [47]:
Arr = np.array([[1,1],[2,3]])
print(Arr)

[[1 1]
 [2 3]]


In [49]:
Arr = np.unique(Arr)
Arr

array([1, 2, 3])

## Exercise 7: Change the dimension of an array


Original array: [1 2 3 4 5 6 7 8 9]
Change array shape to (3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
Arr = np.arange(1,10)
print(Arr)

[1 2 3 4 5 6 7 8 9]


In [53]:
Arr = Arr.reshape(3,3)
print(Arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Exercise 8: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


In [54]:
Arr = np.linspace(2.5,6.5,30)
print(Arr)

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


## Exercise 9: Convert 1-D arrays as columns into a 2-D array

Array1: [10 20 30]
Array2: [40 50 60]
Converted array
[[10 40]
 [20 50]
 [30 60]]


In [60]:
Arr1 = np.array([10,20,30])
Arr2 = np.array([40,50,60])
Arr3 = np.stack((Arr1,Arr2))
Arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [61]:
res = np.transpose(Arr3)
print(res)

[[10 40]
 [20 50]
 [30 60]]


## Exercise 10: Create a 5x5 matrix with row values ranging from 0 to 4

Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [69]:
Arr = np.zeros((5,5))
print(Arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [70]:
Arr += np.arange(5)
print(Arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## Exercise 11: Sum of all the multiples of 3 or 5 below 100

In [76]:
list1 = []
for i in range(100):
    if((i%3 == 0) | (i%5 ==0)):
        list1.append(i)

res = np.asarray(list1)
print(res)

[ 0  3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50
 51 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]


## Exercise 12: Combine a one and a two dimensional array together and display their elements
##### Hint : np.nditer()

In [28]:
x = np.arange(4)
y = np.arange(4)
for a, b in np.nditer([x,y]):
    print(a)
    print(b)

0
0
1
1
2
2
3
3


One dimensional array:
[0 1 2 3]
Two dimensional array:
[[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


In [87]:
Arr1 = np.array([0,1,2,3])
Arr2 = np.array([[0,1,2,3],[4,5,6,7]])

In [90]:
for a,b in np.nditer([Arr1,Arr2]):
    print(a,':',b)

0 : 0
1 : 1
2 : 2
3 : 3
0 : 4
1 : 5
2 : 6
3 : 7


## Exercise 13: Write a NumPy program to replace all elements of NumPy array that are greater than specified array.

Original array:
[[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5
[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


In [91]:
Arr = np.array([[0.42436315, 0.48558583, 0.32924763],
 [0.7439979,  0.58220701, 0.38213418],
 [0.5097581,  0.34528799, 0.1563123 ]])


[[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]


In [95]:
Arr[Arr > .5] = .5
print(Arr)

[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


## Exercise 14: Add a new row to an empty numpy array

Empty array:
[]
After adding two new arrays:
[[10 20 30]
 [40 50 60]]


In [96]:
Arr = np.empty((0,3),int)

array([], shape=(0, 3), dtype=int32)

In [101]:
Arr = np.append(Arr,np.array([[10,20,30]]),axis =0)

In [102]:
Arr = np.append(Arr,np.array([[40,50,60]]),axis =0)

In [103]:
print(Arr)

[[10 20 30]
 [40 50 60]]


## Exercise 15: Write a NumPy program to join a sequence of arrays along a new axis. 

Original arrays:
[1 2 3]
[2 3 4]
Sequence of arrays along a new axis:
[[1 2 3]
 [2 3 4]]

Original arrays:
[[1]
 [2]
 [3]]

[[2]
 [3]
 [4]]
Sequence of arrays along a new axis:
[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]


In [105]:
Arr1 = np.array([1, 2, 3])
Arr2 = np.array([2, 3, 4])
print(np.vstack((Arr1,Arr2)))

[[1 2 3]
 [2 3 4]]


In [106]:
Arr1 = np.array([[1], [2], [3]])
Arr2 = np.array([[2], [3], [4]])
print(Arr1)
print(Arr1)

[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]


In [107]:
print(np.vstack((Arr1,Arr2)))

[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]
